=== icprog/sti-deprecated/server/vcproject/series.dtd
<!ELEMENT series (title,date,desc?,timing,experiments)>

<!ELEMENT title (#PCDATA)>

<!ELEMENT date (#PCDATA)>

<!ELEMENT desc (#PCDATA)>

<!ELEMENT timing (file+,var*)>

<!ELEMENT file (#PCDATA)>

<!ELEMENT var (name,val?)>
<!ATTLIST var id ID #REQUIRED>

<!ELEMENT name (#PCDATA)>

<!ELEMENT val (#PCDATA)>

<!ELEMENT experiments (experiment+)>

<!ELEMENT experiment (file)>

=== icprog/sti-deprecated/server/vcproject/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE series SYSTEM "series.dtd">
<series>

<title>MOT_time_sweep_1</title>

  <date>Wed Apr  2 22:49:37 2008</date>

  <desc>Sweep MOT_time from 10s to 45s in 5s increments. No CMOT. Detuning @ 6MHz. Looking for maximum final atom number as figure of merit.</desc>
  
  <timing>
    <file>timingfile_main_v1_3-7-2008.py</file>
    <file>timingfile_MOT_v1_3-7-2008.py</file>
    <var id="MOT_time">
      <name>MOT_time</name>
      <val>10s + iter*5s</val>
    </var>
    <var id="MOT_detuning">
      <name>MOT_detuning</name>
      <val>+6MHz</val>
    </var>
    <var id="MOT_beam_intensity">
      <name>MOT_beam_intensity</name>
      <val>50mW/cm^2</val>
    </var>
  </timing>

  <experiments>
    <experiment>
      <file>Experiment_MOT_time_sweep_1_iter0.xhtml</file>
    </experiment>
    <experiment>
      <file>Experiment_MOT_time_sweep_1_iter1.xhtml</file>
    </experiment>
    <experiment>
      <file>Experiment_MOT_time_sweep_1_iter2.xhtml</file>
    </experiment>
    <experiment>
      <file>Experiment_MOT_time_sweep_1_iter3.xhtml</file>
    </experiment>
    <experiment>
      <file>Experiment_MOT_time_sweep_1_iter4.xhtml</file>
    </experiment>
    <experiment>
      <file>Experiment_MOT_time_sweep_1_iter5.xhtml</file>
    </experiment>
    <experiment>
      <file>Experiment_MOT_time_sweep_1_iter6.xhtml</file>
    </experiment>
    <experiment>
      <file>Experiment_MOT_time_sweep_1_iter7.xhtml</file>
    </experiment>
  </experiments>

</series>
